version: '3.8'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ports:
      - "9200:9200"
    networks:
      - pipeline-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - pipeline-net

  spark:
    image: bitnami/spark:3.5.5
    container_name: spark
    environment:
      - SPARK_MODE=master
    ports:
      - "4040:4040"
    networks:
      - pipeline-net

  spark-worker:
    image: bitnami/spark:3.5.5
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
    depends_on:
      - spark
    networks:
      - pipeline-net

  nifi:
    image: apache/nifi:2.3.0
    container_name: nifi
    environment:
      - NIFI_WEB_HTTP_PORT=8443
      - NIFI_WEB_HTTPS_HOST=0.0.0.0
      - NIFI_WEB_HTTPS_PORT=
    ports:
      - "8443:8443"
    networks:
      - pipeline-net

networks:
  pipeline-net:
    driver: bridge